apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iridium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iridium
  name: iridium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iridium
  template:
    metadata:
      labels:
        app: iridium
    spec:
      volumes:
        - name: config
          configMap:
            name: iridium
        - name: data
          persistentVolumeClaim:
            claimName: iridium
      containers:
        - name: iridium
          image: "ghcr.io/avaraline/iridium"
          imagePullPolicy: Always
          ports:
            - containerPort: 6667
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/etc/iridium.toml"
              subPath: iridium.toml
            - name: data
              mountPath: "/data"
---
apiVersion: v1
kind: Service
metadata:
  name: iridium
spec:
  type: NodePort
  selector:
    app: iridium
  ports:
    - port: 6667
      protocol: TCP
      targetPort: 6667
      nodePort: 31667
